server:
  port: ${dev.eureka.server.port}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8500/eureka/

spring:
  rabbitmq:
    host: 192.168.124.128
    #nginx端口，也可以是rabbit的
    port: 8081
    password: guest
    username: guest
  redis:
    host: 192.168.124.128
    port: 6379
    timeout: 20000
    cluster:
      nodes: 192.168.124.128:6380,192.168.124.128:6381,192.168.124.128:6382,192.168.124.128:6383,192.168.124.128:6384
      maxRedirects: 6
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
  boot:
    admin:
      client:
        url: http://localhost:3333

feign:
  hystrix:
    enabled: true
