server:
  port: 9772

spring:
  profiles:
    active: prod2
  redis:
    key-prefix: prod  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）

logging:
  level:
    console: WARN
    filter: WARN


# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。