info:
  artifact: zuihou-file-server
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
  spring-cloud-version: '@spring.cloud.version@'

# 日志
logging:
  path: ./logs/zuihou-file-server
  file: ${logging.path}/root.log
  common-pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS}:[%5p] [%t:%r] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO
    rest: INFO
    service: INFO
    sql: DEBUG

# 端口号
server:
  port: 9755

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
    status-page-url: http://${zuihou.hostname.gateway:gateway.zuihou.com}:9770/api/file/swagger-ui.html
#    hostname: ${eureka.hostname:eureka.zuihou.com}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

# bean 转换
dozer:
  mappingFiles: classpath*:dozer/*.dozer.xml

# spring配置
spring:
  application:
    name: zuihou-file-server
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 2000Mb      # Max file size，默认1M
      max-request-size: 2500Mb   # Max request size，默认10M
  redis:
    host: zuihou.redis.host
    port: 6379
    pool:
      max-active: 100
      min-idle: 2
      max-idle: 8
      max-wait: 100
    key-prefix: dev
  rabbitmq:
    host: zuihou.rabbitmq.host
    port: 5672               # 根据环境更改
    password: guest          # 根据环境更改
    username: guest          # 根据环境更改
  sleuth:
    sampler:
      percentage: 0.5
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
#    base-url: http://zuihou-zipkin:8510
    locator:
      discovery:
        enabled: true
    service:
      name: ${spring.application.name}
#    rabbitmq:
#      queue: zipkin

# actuator端点 以及 actuator端点的权限
management:
  security:
    enabled: true
  context-path: /mgmt
security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  # actuator的health接口是否需要安全保证

feign:
  hystrix:
    enabled: true

hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# 文档配置
swagger2:
  package: com.github.zuihou.file.rest
  service:
    name: 文件服务
    description: 文件服务
    contact:
      name: 最后
      url: http://www.zuihou.com/
      email: tangstruggle@sina.com

# 认证客服端配置
auth:
  serviceId: zuihou-auth-server
  app:
    token-header: token # 其三方应用token
    pub-key:
      path: app/pub.key
  client:
    id: zuihou-file-server
    secret: 123456
    token-header: token
    admin-header: _isAdmin
    pub-key:
      path: client/pub.key

 # id生成器机器掩码
id-generator:
  machine-code: 1

# 文件上传相关信息
zuihou:
  mysql:
    file:
      database: zuihou_file_dev       # 根据环境更改
      driverClassName: ${zuihou.mysql.driverClassName}
      host: ${zuihou.mysql.host}
      password: ${zuihou.mysql.password}
      port: ${zuihou.mysql.port}
      url: jdbc:mysql://${zuihou.mysql.file.host}:${zuihou.mysql.file.port}/${zuihou.mysql.file.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: ${zuihou.mysql.username}
    driverClassName: com.mysql.cj.jdbc.Driver  # 6.0.6
    host: zuihou.mysql.host     # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==
  file:
    upload-path-prefix: /home/zuihou/uploadfile/
    remote-uri-prefix: http://192.168.65.147:6080/
    fastdfs:
      enabled: true
  hostname:
    gateway: 127.0.0.1
