server:
  port: 9755

spring:
  redis:
    key-prefix: dev  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）
    host: zuihou.redis.host
    port: 6379

zuihou:
  mysql:
    file:
      database: zuihou_file_dev       # 根据环境更改
    host: zuihou.mysql.host     # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==
  file:
    upload-path-prefix: D:\home\uploadfile\
    remote-uri-prefix: http://192.168.65.147:6080/
    fastdfs:
      enabled: false
  hostname:
    gateway: 127.0.0.1

 # id生成器机器掩码
id-generator:
  machine-code: 1