logging:
  level:
    console: WARN

spring:
  rabbitmq:
    host: zuihou.rabbitmq.host # 在hosts文件中配置地址
    port: 5672
    username: guest
    password: guest
# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。