server:
  port: ${dev.eureka.server.port}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    metadata-map:
      version: v1
      my-metadata: v1
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    service-url:
      defaultZone: http://127.0.0.1:8500/eureka/


#spring:
#  rabbitmq:
#    addresses: 192.168.124.128:5672,192.168.124.128:5673,192.168.124.128:5674
#    password: guest
#    username: guest

spring:
  rabbitmq:
    addresses: 47.102.115.83:5672,47.102.115.83:5673,47.102.115.83:5674
    password: guest
    username: guest
    listener:
      simple:
        retry:
          enabled: false #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5 #最大重试次数
          initial-interval: 5000 #重试间隔时间（单位毫秒）
          max-interval: 1200000 #重试最大时间间隔（单位毫秒）
          multiplier: 5 #应用于前一重试间隔的乘法器
  redis:
    host: 47.102.115.83
    port: 8888
    timeout: 20000
    fail-fast: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/news-service?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size:  5
    1
  boot:
    admin:
      client:
        url: http://localhost:3333
mybatis:
  typeAliasesPackage: com.han.newsservice.pojo
  mapperLocations: classpath:mapper/*.xml

feign:
  hystrix:
    enabled: true
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule

