
prod1:
  eureka:
    server:
      port: 6501
    hostname: apigate.hw.com
dev:
  eureka:
    server:
      port: 6503
    hostname: 127.0.0.1

# 公共配置
spring:
  profiles:
    active: dev
  application:
    name: api-gateway
#  redis:
#    cache.clusterNodes: 47.102.115.83:6379,47.102.115.83:6380,47.102.115.83:6381,47.102.115.83:6382,47.102.115.83:6383,47.102.115.83:6384
#    cache.commandTimeout: 5000
  redis:
    host: 47.102.115.83
    port: 9999
    timeout: 20000
    password: redis
#  redis:
#    host: 47.102.115.83
#    port: 6379
#    timeout: 20000
#    cluster:
#      nodes: 47.102.115.83:6380,47.102.115.83:6381,47.102.115.83:6382,47.102.115.83:6383,47.102.115.83:6384
#      maxRedirects: 6
#    fail-fast: true
  pool:
    max-active: 8
    min-idle: 0
    max-idle: 8
    max-wait: -1

management:
  context-path: /api-gateway
#  endpoints:
#    web:
#      exposure:
#        include: *


info:
  artifact: api-gateway
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
  spring-cloud-version: '@spring.cloud.version@'