server:
  port: ${dev.eureka.server.port}

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8500/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
    serviceId: hello-provide
  SendErrorFilter:
    error:
      disable: true

