server:
  port: 9777

spring:
  profiles:
    active: prod2
  redis:
    key-prefix: prod  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）
    host: zuihou.redis.host
  rabbitmq:
    host: zuihou.rabbitmq.host
    port: 5672
    username: guest
    password: guest

zuihou:
  mysql:
    admin:
      database: zuihou_admin_prod

logging:
  level:
    console: WARN
    filter: WARN

id-generator:
  machine-code: 2  # id生成器机器掩码


# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。