spring:
  profiles:
    active: prod
  rabbitmq:
    host: zuihou.rabbitmq.host # 在hosts文件中配置地址
    port: 5672
    username: guest
    password: guest
  datasource:
#    url: jdbc:mysql://zuihou.mysql.host:3306/zuihou_zipkin_prod?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    url: jdbc:mysql://zuihou.mysql.host:3306/zuihou_zipkin_prod?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root  # 这里不需要加密
# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。

logging:
  level:
    console: WARN