server:
  port: ${dev.eureka.server.port}

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8500/eureka/


#spring:
#  rabbitmq:
#    addresses: 192.168.124.128:5672,192.168.124.128:5673,192.168.124.128:5674
#    password: guest
#    username: guest

spring:
  rabbitmq:
    addresses: 192.168.124.128:2222
    password: guest
    username: guest
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hello-test?useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size:  5

mybatis:
  typeAliasesPackage: com.han.helloservice.pojo
  mapperLocations: classpath:mapper/UserMapper.xml

feign:s
  hystrix:
    enabled: true
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule

