prod1:
  eureka:
    server:
      port: 9502
    hostname: eureka1.hw.com
dev:
  eureka:
    server:
      port: 9502
    hostname: 127.0.0.1

# 公共配置
spring:
  profiles:
    active: dev
  application:
    name: HELLO-PROVIDE


management:
  context-path: /HELLO-PROVIDE
#  endpoints:
#    web:
#      exposure:
#        include: *


info:
  artifact: HELLO-PROVIDE
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
  spring-cloud-version: '@spring.cloud.version@'